"""Writes public/sitemap.xml — the shop, plus one URL per garment.

    python scripts/make_sitemap.py

Run it after a drop, alongside sync_inventory.py: a sitemap is a snapshot, and
an item added since the last run is one Google has no reason to look for.

Sold items are listed too. Their pages still answer, and a sold garment that
ranks is how someone finds the shop looking for the next one. They drop out on
their own when the 1st/15th reset clears them and this is next run.

The slug rules live in shared/slug.mjs, which the browser and the Netlify
function both import. They are re-stated here because Python cannot import it;
if that file changes, change this too.
"""

import json
import os
import re
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import d1
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "public", "sitemap.xml")
SHOP = "https://hightide-vintage.netlify.app"


def load_env():
    """Minimal .env reader — avoids a python-dotenv dependency."""
    path = os.path.join(ROOT, ".env")
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def slugify(text: str) -> str:
    """Mirror of slugify() in shared/slug.mjs."""
    return re.sub(r"^-+|-+$", "", re.sub(r"[^a-z0-9]+", "-", str(text).lower()))


def fetch_items():
    # sold comes back as 0/1 from SQLite; the writer below tests it truthily,
    # which works either way, but normalise so the two cannot drift.
    rows = d1.query("SELECT num, name, sold FROM items ORDER BY num ASC")
    for row in rows:
        row["sold"] = bool(row["sold"])
    return rows


def main() -> None:
    load_env()
    items = fetch_items()

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/make_sitemap.py. Do not edit by hand. -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        "  <url>",
        f"    <loc>{SHOP}/</loc>",
        "    <changefreq>weekly</changefreq>",
        "    <priority>1.0</priority>",
        "  </url>",
    ]

    # Categories rank for what people actually type — "מכנסי גלישה וינטג׳" —
    # which no single garment's page competes for. Kept in step with
    # shared/categories.mjs by hand; there are five of them.
    for category in ("all", "boardies", "shirts", "accessories", "women", "latest"):
        lines += [
            "  <url>",
            f"    <loc>{SHOP}/category/{category}</loc>",
            "    <changefreq>weekly</changefreq>",
            "    <priority>0.9</priority>",
            "  </url>",
        ]

    for item in items:
        name = slugify(item.get("name") or "")
        num = item["num"]
        slug = f"{name}-{num}" if name else str(num)
        lines += [
            "  <url>",
            f"    <loc>{SHOP}/product/{slug}</loc>",
            "    <changefreq>weekly</changefreq>",
            # A sold garment is still worth indexing, just not ahead of one
            # somebody can actually buy.
            f"    <priority>{'0.4' if item.get('sold') else '0.8'}</priority>",
            "  </url>",
        ]

    lines.append("</urlset>")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    sold = sum(1 for i in items if i.get("sold"))
    print(f"{len(items)} products ({len(items) - sold} available, {sold} sold) -> {OUT}")


if __name__ == "__main__":
    main()
